routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/

Route::get('/', function () {
    return view('welcome');
});

Auth::routes();

	Route::resource('registrar','Auth\RegisterController');


	
Route::get('/home', 'HomeController@index');

Route::post('logout',['as'=>'logout','uses'=>"Auth\LoginController@logout"]);
Route::get('/logout', function(){
	Auth::logout();
	return redirect('/');
});
Route::post('contact/store', ['as'=>'contact/store', 'uses'=>'ContactController@store']);

Route::get('message', 'ContactController@index');
Route::get('message/ver/{id}', ['as' => 'message/ver', 'uses'=>'ContactController@view']);
Route::get('message/{id}', ['as' => 'message', 'uses'=>'ContactController@view']);
Route::get('services', 'ServiceController@index');
Route::get('profile', 'ProfileController@index');
Route::get('editarperfil', 'ProfileController@edit');
Route::post('service/update', 'ServiceController@update');
Route::get('projects', 'projectController@index');
Route::get('service/add', 'ServiceController@nuevo');
Route::get('project/add', 'projectController@nuevo');
Route::post('service/store', ['as'=>'service/store', 'uses'=>'ServiceController@store']);
Route::post('project/store', ['as'=>'project/store', 'uses'=>'projectController@store']);
Route::post('guardarperfil', ['as'=>'guardarperfil', 'uses'=>'ProfileController@update']);
Route::post('project/update', 'projectController@update');
Route::get('service/{id}', ['as'=>'service', 'uses'=>'ServiceController@edit']);
Route::get('project/{id}', ['as'=>'project', 'uses'=>'projectController@edit']);
Route::get('cargaEventos{id?}','CalendarController@index');
Route::post('guardaEventos', array('as' => 'guardaEventos','uses' => 'CalendarController@create'));
Route::post('actualizaEventos','CalendarController@update');
Route::post('eliminaEvento','CalendarController@delete');
Route::post('guardarImagenes','HomeController@imagen');
Route::get('imagenes','imagenesController@index');
Auth::routes();

Route::get('/home', 'HomeController@index');

resources/views/cambiarimagenes.blade.php
<?php

 use App\Models\imagen;
  
  $imagens = imagen::all();
?>
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
      <form method="post" action="{{ url('/guardarImagenes') }}"  enctype="multipart/form-data">  
        {{ csrf_field() }}
 <div class="col-md-11 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Imagenes</div>

                <div class="panel-body ">
            
		
		@foreach ($imagens as $img)
                    <div class="row col-md-10 col-md-offset-1" >
          
                	<img class="img-responsive" width="" src="profile_pictures/{{$img->image1}}">
                	<br>
                	<input type="file" name="img1" class="btn btn-perro">
                </div>

                  <div class="row col-md-10 col-md-offset-1" >
          
                    <img class="img-responsive" width="" src="profile_pictures/{{$img->image2}}">
                    <br>
                    <input type="file" name="img2" class="btn btn-perro">
                </div>

                  <div class="row col-md-10 col-md-offset-1" >
          
                    <img class="img-responsive" width="" src="profile_pictures/{{$img->image3}}">
                    <br>
                    <input type="file" name="img3" class="btn btn-perro">
                </div>
       @endforeach
                <br>
                <div class="row col-md-10">
                    <input type="submit" name="Guardar" class="btn btn-perro" value="Guardar">
               
                  </div>
                </div>
            </div>
        </div>
    </form>
    </div>
</div>
@endsection

resources/views/contact.blade.php
  <section id="contact" class="home-section nopadd-bot color-dark bg-white text-center">
  
        <div class="container marginbot-50">
            <div class="row">
                <div class="col-lg-8 col-lg-offset-2">
                    <div class="wow flipInY" data-wow-offset="0" data-wow-delay="0.4s">
                    <div class="section-heading text-center">
                    <h2 class="h-bold">Contact</h2>
                    <div class="divider-header"></div>
                   
                    </div>
                    </div>
                </div>
            </div>

        </div>
        
        <div class="container">

            <div class="row marginbot-80">
                <div class="col-md-8 col-md-offset-2">
                        <div id="sendmessage">Your message has been sent. Thank you!</div>
                        <div id="errormessage"></div>
       
                     <form class="form-horizontal" role="form" method="POST" action="{{ url('/contact/store') }}">
                             {{ csrf_field() }}

                            <div class="form-group">
                                <input type="text" name="name" class="form-control" id="name" placeholder="Your Name" data-rule="minlen:4" data-msg="Please enter at least 4 chars" />
                                <div class="validation"></div>
                            </div>
                            <div class="form-group">
                                <input type="email" class="form-control" name="email" id="email" placeholder="Your Email" data-rule="email" data-msg="Please enter a valid email" />
                                <div class="validation"></div>
                            </div>
                            <div class="form-group">
                                <input type="text" class="form-control" name="subject" id="subject" placeholder="Subject" data-rule="minlen:4" data-msg="Please enter at least 8 chars of subject" />
                                <div class="validation"></div>
                            </div>
                            <div class="form-group">
                                <textarea class="form-control" name="message" rows="5" data-rule="required" data-msg="Please write something for us" placeholder="Message"></textarea>
                                <div class="validation"></div>
                            </div>
                            
                            <div class="text-center"><button type="submit" class="btn btn-skin btn-lg btn-block">Send Message</button></div>

                            <input type="number"  style="visibility:hidden" name="estado_id" value="1">
                        </form>
                        
                </div>
            </div>  


        </div>
            
    </section>

resources/views/crearProject.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        
 <div class="col-md-11 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">

                     <form class="form-horizontal" role="form" method="POST" action="{{ url('/project/store') }}">
                         {{ csrf_field() }}
                        
                    <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                            <label for="image" class="col-md-4 control-label">Imagen: </label>

                            <div class="col-md-6">
                                <input id="image" type="text" class="form-control" name="image" value="" required>

                                @if ($errors->has('image'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                  
         
                      <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nombre: </label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="" required>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                  
                   
                      <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Descripcion: </label>

                            <div class="col-md-6">

                                <textarea id="description" type="text" class="form-control" name="description"  required></textarea>

                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>

                        </div>
                    <div class="form-group{{ $errors->has('estado_id') ? ' has-error' : '' }}">
                         <label for="estado_id" class="col-md-4 control-label">Estado: </label>
                    <div class="col-md-6">
                        
                    <select name="estado_id"  class="form-control">
                        @foreach($Estados as $pais)
                                                <option value="{{$pais->id}}">{{$pais->nombre}}</option>
                                             
                                        
                                                 @endforeach
                                          
                        
                    </select>
                </div>
                     @if ($errors->has('estado_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('estado_id') }}</strong>
                                    </span>
                                @endif
                    </div>
                   <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-skin">
                                    Guardar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/crearService.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        
 <div class="col-md-11 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">

                     <form class="form-horizontal" role="form" method="POST" action="{{ url('/service/store') }}">
                         {{ csrf_field() }}
                        
                    <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                            <label for="image" class="col-md-4 control-label">Imagen: </label>

                            <div class="col-md-6">
                                <input id="image" type="text" class="form-control" name="image" value="" required>

                                @if ($errors->has('image'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                  
         
                      <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nombre: </label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="" required>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                  
                   
                      <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Descripcion: </label>

                            <div class="col-md-6">

                                <textarea id="description" type="text" class="form-control" name="description"  required></textarea>

                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>

                        </div>
                    <div class="form-group{{ $errors->has('estado_id') ? ' has-error' : '' }}">
                         <label for="estado_id" class="col-md-4 control-label">Estado: </label>
                    <div class="col-md-6">
                        
                    <select name="estado_id"  class="form-control">
                        @foreach($Estados as $pais)
                                                <option value="{{$pais->id}}">{{$pais->nombre}}</option>
                                             
                                        
                                                 @endforeach
                                          
                        
                    </select>
                </div>
                     @if ($errors->has('estado_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('estado_id') }}</strong>
                                    </span>
                                @endif
                    </div>
                   <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-skin">
                                    Guardar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/editProfile.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        
 <div class="col-md-11 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Perfil</div>

                <div class="panel-body">
                 <form class="form-horizontal" role="form" method="POST" action="{{ url('/guardarperfil') }}"
                  enctype="multipart/form-data">
                 {{ csrf_field() }}
                <div class="col-md-3">
                <center>
                    <input type="hidden" name="id" value="{{$Usuario->id}}">
                    <img src="profile_pictures/{{$Usuario->img}}"  class="img-thumbnail">
                    <br>
                    <br>
                   <input class="btn -btn-perro" type="file" name="img" value="{{$Usuario->img}}">
                   
                </center>
                </div>
                <div class="col-md-8">

                <input class="form-control" type="text" name="name" value="{{$Usuario->name}}">
                <input class="form-control" type="text" name="last_name" value=" {{$Usuario->last_name}}">
               <input class="form-control" type="text" name="email" value="{{$Usuario->email}}">
                
                       

                                   <select id="pais_id" name="pais_id"  class="form-control" required>
                                            
                                            @foreach($Paises as $pais)
                                                @if($Usuario->pais_id == $pais->id) 
                                                <option selected value="{{$pais->id}}">{{$pais->nombre}}</option>
    
                                             @else
                                            <option value="{{$pais->id}}">{{$pais->nombre}}</option>
                                                 @endif
                                            @endforeach
                                        </select>
                     
           
                             
                         

                                   <select id="rol_id" name="rol_id"  class="form-control" required>
                                            
                                            @foreach($Roles as $rol)
                                             @if($Usuario->rol_id == $rol->id) 
                                                <option selected value="{{$rol->id}}">{{$rol->nombre}}</option>
    
                                             @else
                                            <option value="{{$pais->id}}">{{$rol->nombre}}</option>
                                                 @endif
                                               
                                            @endforeach
                                        </select>
                     
                             
             
       
            <br>
                    <br>
                    <input class="btn btn-perro" type="submit" name="Guardar" value="Guardar">
          
            </div>
                  </form>

                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/editProject.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        
 <div class="col-md-11 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">

                     <form class="form-horizontal" role="form" method="POST" action="{{ url('/project/update') }}">
                        {{ csrf_field() }}
                         <input id="id" type="hidden" class="form-control" name="id" value="{{$Proyectos->id}}" required>
                    <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                            <label for="image" class="col-md-4 control-label">Imagen: </label>

                            <div class="col-md-6">
                                <input id="image" type="text" class="form-control" name="image" value="{{$Proyectos->image}}" required>

                                @if ($errors->has('image'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                    <img src="">
         
                      <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nombre: </label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{$Proyectos->name}}" required>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                  
                   
                      <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Descripcion: </label>

                            <div class="col-md-6">

                                <textarea id="description" type="text" class="form-control" name="description"  required>{{$Proyectos->description}}</textarea>

                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>

                        </div>
                    <div class="form-group{{ $errors->has('state_id') ? ' has-error' : '' }}">
                         <label for="state_id" class="col-md-4 control-label">Estado: </label>
                    <div class="col-md-6">
                        
                    <select name="state_id"  class="form-control">
                        @foreach($Estados as $pais)

                                                @if($Proyectos->estado_id == $pais->id) 
                                                <option selected value="{{$pais->id}}">{{$pais->nombre}}</option>
    
                                             @else
                                            <option value="{{$pais->id}}">{{$pais->nombre}}</option>
                                                 @endif
                                                 @endforeach
                                          
                        
                    </select>
                </div>
                     @if ($errors->has('state_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('state_id') }}</strong>
                                    </span>
                                @endif
                    </div>
                   <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-skin">
                                    Guardar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/editService.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        
 <div class="col-md-11 col-md-offset-1">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">

                     <form class="form-horizontal" role="form" method="POST" action="{{ url('/service/update') }}">
                        {{ csrf_field() }}
                         <input id="id" type="hidden" class="form-control" name="id" value="{{$Servicios->id}}" required>
                    <div class="form-group{{ $errors->has('image') ? ' has-error' : '' }}">
                            <label for="image" class="col-md-4 control-label">Imagen: </label>

                            <div class="col-md-6">
                                <input id="image" type="text" class="form-control" name="image" value="{{$Servicios->image}}" required>

                                @if ($errors->has('image'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('image') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                    <img src="">
         
                      <div class="form-group{{ $errors->has('name') ? ' has-error' : '' }}">
                            <label for="name" class="col-md-4 control-label">Nombre: </label>

                            <div class="col-md-6">
                                <input id="name" type="text" class="form-control" name="name" value="{{$Servicios->name}}" required>

                                @if ($errors->has('name'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('name') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>
                  
                   
                      <div class="form-group{{ $errors->has('description') ? ' has-error' : '' }}">
                            <label for="description" class="col-md-4 control-label">Descripcion: </label>

                            <div class="col-md-6">

                                <textarea id="description" type="text" class="form-control" name="description"  required>{{$Servicios->description}}</textarea>

                                @if ($errors->has('description'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('description') }}</strong>
                                    </span>
                                @endif
                            </div>

                        </div>
                    <div class="form-group{{ $errors->has('state_id') ? ' has-error' : '' }}">
                         <label for="state_id" class="col-md-4 control-label">Estado: </label>
                    <div class="col-md-6">
                        
                    <select name="state_id"  class="form-control">
                        @foreach($Estados as $pais)

                                                @if($Servicios->estado_id == $pais->id) 
                                                <option selected value="{{$pais->id}}">{{$pais->nombre}}</option>
    
                                             @else
                                            <option value="{{$pais->id}}">{{$pais->nombre}}</option>
                                                 @endif
                                                 @endforeach
                                          
                        
                    </select>
                </div>
                     @if ($errors->has('state_id'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('state_id') }}</strong>
                                    </span>
                                @endif
                    </div>
                   <div class="form-group">
                            <div class="col-md-6 col-md-offset-4">
                                <button type="submit" class="btn btn-skin">
                                    Guardar
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/home.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
        <div class="col-md-8 col-md-offset-2">
            <div class="panel panel-default">
                <div class="panel-heading">Dashboard</div>

                <div class="panel-body">
                    You are logged in!
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/login.blade.php
<div id="myModal" class="modal fade" role="dialog">
  <div class="modal-dialog">

    <!-- Modal content-->
    <div class="modal-content">
      <div class="modal-header">
        <button type="button" class="close" data-dismiss="modal">&times;</button>
        <h4 class="modal-title">Login</h4>
      </div>
      <div class="modal-body">
        <form class="form-horizontal" role="form" method="POST" action="{{ url('/login') }}">
                        {{ csrf_field() }}

                        <div class="form-group{{ $errors->has('email') ? ' has-error' : '' }}">
                            <label for="email" class="col-md-4 control-label">E-Mail Address</label>

                            <div class="col-md-6">
                                <input id="email" type="email" class="form-control" name="email" value="{{ old('email') }}" required autofocus>

                                @if ($errors->has('email'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('email') }}</strong>
                                    </span>
                                @endif
                            </div>
                        </div>

                        <div class="form-group{{ $errors->has('password') ? ' has-error' : '' }}">
                            <label for="password" class="col-md-4 control-label">Password</label>

                            <div class="col-md-6">
                                <input id="password" type="password" class="form-control" name="password" required>

                                @if ($errors->has('password'))
                                    <span class="help-block">
                                        <strong>{{ $errors->first('password') }}</strong>
                                    </span>
                                @endif

                            </div>
                        </div>


                        <div class="form-group">
                            <div class="col-md-8 col-md-offset-4">
                                <button type="submit" class="btn btn-skin">
                                    Login
                                </button>

                        

                                <a type="button" class="btn bt-colora"  href="{{ route('registrar.index') }}" > Register </a>

                              

                                <a class="btn btn-link" href="{{ url('/password/reset') }}">
                                    Forgot Your Password?
                                </a>
                            </div>
                        </div>
                    </form>
      </div>
      <div class="modal-footer">
        <button type="button" class="btn btn-skin" data-dismiss="modal">Close</button>
   
      
      </div>
    </div>

  </div>
</div>